# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

delaunayXYZ_linear <- function(XYZ) {
    .Call(`_interpolation_delaunayXYZ_linear`, XYZ)
}

interpolate_linear <- function(xptr, XYnew) {
    .Call(`_interpolation_interpolate_linear`, xptr, XYnew)
}

delaunayXYZ_sibson <- function(XYZ) {
    .Call(`_interpolation_delaunayXYZ_sibson`, XYZ)
}

interpolate_sibson <- function(xptr, XYnew) {
    .Call(`_interpolation_interpolate_sibson`, xptr, XYnew)
}

